import Head from 'next/head';
import Transactions from '../components/Transactions/Transactions';
import Hero from '../components/Hero/Hero';
import Navigation from '../components/Navigation/Navigation';
import Perks from '../components/Perks/Perks';
import HardWorking from '../components/HardWorking/HardWorking';
import { useTheme } from 'next-themes';
import { useEffect, useState } from 'react';
import Toolbreak from '../components/Toolbreak/Toolbreak';
import Footer from '../components/Footer/Footer';

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { setTheme, resolvedTheme, theme } = useTheme();

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div id="root" className=" min-h-screen min-w-screen font-sans">
      <Head>
        <title>Berkshire Hathaway</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap"
          rel="stylesheet"
        />
      </Head>

      {mounted && (
        <main className="bg-[#dfdede] dark:bg-background w-full h-full font-sans ">
          <Navigation />
          <Hero />
          <HardWorking />
          <Transactions />
          <Perks />
          <Toolbreak />
          <Footer />
        </main>
      )}
    </div>
  );
}
